development:
  host: <%= ENV['DATABASE_HOST'] %>
  adapter: postgresql
  encoding: unicode
  database: word_a_day_dev
  pool: 5

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: word_a_day_prod
  pool: 5
